name: 'Terraform Detect Changes'
description: 'GitHub Action for detecting changes to terraform files'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  included-paths:
    description: "Comma-separated paths to narrow down the search for terraform changes. Defaults to all if not specified."
    required: false
    default: ""
  if-these-paths-change-return-all-included-paths:
    description: "If the any terraform files on the following paths change, return all included files. (Comma-separated)"
    required: false
    default: ""
outputs:
  changed:
    description: "JSON encoded object that contains the changed files. '{ changed: Array<string> }'"
    value: ${{ steps.detect.outputs.changed }}
runs:
  using: "composite"
  steps:
    - uses: tchupp/actions-detect-directory-changes@v1
      id: detect
      with:
        included-paths: ${{ inputs.included-paths }}
        included-extensions: "tf"
        if-these-paths-change-return-all-included-paths: ${{ inputs.if-these-paths-change-return-all-included-paths }}
