name: build+test1

on:
  - pull_request

jobs:
  terraform-detect-changes:
    name: "Terraform Detect Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.action.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Terraform Changes
        uses: ./
        id: action

      - name: check output
        shell: bash
        run: |
          echo "${{ steps.action.outputs.changed }}"

  echo-test:
    name: "Echo Test"
    needs: terraform-detect-changes
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.terraform-detect-changes.outputs.changed }}"
          echo "${{ needs.terraform-detect-changes.outputs.changed.changed }}"

  terraform:
    name: "Terraform"
    needs: terraform-detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.terraform-detect-changes.outputs.changed.changed) }}
        env:
          - development
          - staging
          - production
    env:
      TF_WORKSPACE: "${{ matrix.path }}-${{ matrix.env }}"
    steps:
      - name: Checkout
        run: |
          echo "path: ${{ matrix.path }}"
          echo "env: ${{ matrix.env }}"
