name: build+test1

on:
  - pull_request

jobs:
  terraform-detect-changes:
    name: "Terraform Detect Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.action.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Terraform Changes
        uses: ./
        id: action

  terraform:
    name: "Terraform"
    needs: terraform-detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ${{ fromJSON(needs.terraform-detect-changes.outputs.changed) }}
        env:
          - development
          - staging
          - production
    env:
      TF_WORKSPACE: "${{ matrix.path }}-${{ matrix.env }}"
    steps:
      - name: Checkout
        run: |
          echo "path: ${{ matrix.path }}"
          echo "env: ${{ matrix.env }}"
